---
- hosts: rancher
  tasks:
    - name: "Install pre-requisites"
      yum: name=docker state=latest
      become: true
    - name: "Starting docker service"
      service: state=started name=docker
      become: true
