---
- hosts: saas_backend
  tasks:
      - name: "Install pre-requisites"
        yum: name=docker state=latest
        become: true
      - name: "Enabling docker service"
        service: enabled=yes name=docker
        become: true
      - name: "Starting docker service"
        service: state=started name=docker
        become: true
      - name: "Creating Mysql data container"
        command: "docker run --name kdi-mysql-data -e MYSQL_ROOT_PASSWORD=kditest -e MYSQL_DATABASE=kdi mysql echo hello"
        become: true
      - name: "Starting Mysql container"
        command: "docker run --name kdi-mysql -e MYSQL_DATABASE=kdi -e MYSQL_ROOT_PASSWORD=testit -p 3306:3306 -d --volumes-from=kdi-mysql-data mysql"
        become: true

